// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6hP-p3mj5Lq5YZrvt6TUwekTfCqGe4U',
    appId: '1:1030937736205:web:7cc0cdb5f5a064c7cf1144',
    messagingSenderId: '1030937736205',
    projectId: 'mess-friends',
    authDomain: 'mess-friends.firebaseapp.com',
    storageBucket: 'mess-friends.firebasestorage.app',
    measurementId: 'G-MFMD1HG1NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DZA6WMbK2Zn7nIyKKOoHluoMzwXq45k',
    appId: '1:1030937736205:android:087a7f3de11ba738cf1144',
    messagingSenderId: '1030937736205',
    projectId: 'mess-friends',
    storageBucket: 'mess-friends.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXaMqztvDRQy0shBvZSQLzvyrjppu2I2Y',
    appId: '1:1030937736205:ios:e762804c3cd4159dcf1144',
    messagingSenderId: '1030937736205',
    projectId: 'mess-friends',
    storageBucket: 'mess-friends.firebasestorage.app',
    androidClientId: '1030937736205-hq6aa9ap6nebhkitnhdr607un3cs1a8e.apps.googleusercontent.com',
    iosClientId: '1030937736205-3a5cpg2vgv89rdlgt55savr018ulj471.apps.googleusercontent.com',
    iosBundleId: 'com.example.messFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXaMqztvDRQy0shBvZSQLzvyrjppu2I2Y',
    appId: '1:1030937736205:ios:e762804c3cd4159dcf1144',
    messagingSenderId: '1030937736205',
    projectId: 'mess-friends',
    storageBucket: 'mess-friends.firebasestorage.app',
    androidClientId: '1030937736205-hq6aa9ap6nebhkitnhdr607un3cs1a8e.apps.googleusercontent.com',
    iosClientId: '1030937736205-3a5cpg2vgv89rdlgt55savr018ulj471.apps.googleusercontent.com',
    iosBundleId: 'com.example.messFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-6hP-p3mj5Lq5YZrvt6TUwekTfCqGe4U',
    appId: '1:1030937736205:web:104e981fd0f59ab3cf1144',
    messagingSenderId: '1030937736205',
    projectId: 'mess-friends',
    authDomain: 'mess-friends.firebaseapp.com',
    storageBucket: 'mess-friends.firebasestorage.app',
    measurementId: 'G-2T99N1FJDX',
  );

}